### ISSUE TITLE
cannot install under Maven

### ISSUE THREAD

**Issue by monperrus** [electricalwind/data7#1]
I'm trying to compile all projects with Maven. Here are the first steps I'm doing:

```
cd utilitaries/misc
mvn install
cd ../../data7
mvn install
```

This fails (error below). AFAIU, there is a cyclic dependency between `data7-miscUtils` and `data7-parent`.

In what order should I compile?

Thanks!

```
[ERROR] Failed to execute goal on project data7: Could not resolve dependencies for project lu.jimenez.research:data7:jar:1.99-SNAPSHOT: Failed to collect dependencies at lu.jimenez.research:data7-miscUtils:jar:1.99-SNAPSHOT: Failed to read artifact descriptor for lu.jimenez.research:data7-miscUtils:jar:1.99-SNAPSHOT: Could not find artifact lu.jimenez.research:data7-parent:pom:1.99-SNAPSHOT -> [Help 1]
```

**Comment by electricalwind** [comment]
Hello,
to compile the project, just type mvn install from the root directory, i.e., data7-parent, it will set up everything.

Best,

**Comment by monperrus** [comment]
I overlooked the initial pom.xml. Thanks.
